image: node:10.13.0
options:
  docker: true
pipelines:
  custom:
    production:
      - step:
          name: build
          script:
            - yarn install
            - yarn build
      - step:
          name: deploy
          script:
            - scp -r build/* deploy@$PRODUCTION_HOST:/var/w3/html/cme_ff_org/test_deploy/
  branches:
    fix-this-repo:
      - step:
          name: deploy
          script:
            - curl https://cli-assets.heroku.com/install.sh | sh
            - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            - yarn
            - yarn build
            - >
                docker build
                --build-arg USERNAME=$USERNAME
                --build-arg PASSWORD=$PASSWORD
                --build-arg PORT=$PORT
                -t ${HEROKU_SERVER_ID}
                .
            - docker tag ${HEROKU_SERVER_ID} registry.heroku.com/${HEROKU_SERVER_ID}/web
            - docker push registry.heroku.com/${HEROKU_SERVER_ID}/web
            - heroku container:release web --app ${HEROKU_SERVER_ID}
definitions:
  services:
    docker:
      memory: 3072  # increase memory for docker-in-docker from 1GB to 3GB