image: node:10.13.0
pipelines:
  branches:
    master:
      - step:
          name: build and deploy
          script:
            - apt-get update && apt-get install -y rsync
            - yarn install
            - NODE_ENV=production yarn build
            - rsync -av build/ admin@futuresfundamentals.org:/var/w3/html/cme_ff_org/
